#jdbc.driver=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://hadoop102:3306/test_pool?useSSL=false&characterEncoding=utf8
#jdbc.username=root
#jdbc.password=000000

# ???Druid ??????? key?? jdbc. ???
driverClassName=com.mysql.jdbc.Driver
url=jdbc:mysql://hadoop102:3306/test_pool?useSSL=false&characterEncoding=utf8
username=root
password=000000